use chrono::Utc;
use serde::{Deserialize, Serialize};

pub fn now_iso() -> String {
    Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true)
}

pub fn new_id(prefix: &str) -> String {
    format!("{}_{}", prefix, uuid::Uuid::new_v4().simple())
}

// ---------------------------------------------------------------------------
// Gouvernance de dépôt
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum AiAttributionPolicy {
    /// La traçabilité des contributions assistées par IA est exigée : la
    /// suppression des mentions est refusée. Valeur par défaut (conservatrice).
    #[default]
    #[serde(rename = "keep-required")]
    KeepRequired,
    #[serde(rename = "normalization-allowed")]
    NormalizationAllowed,
}

fn default_protected_trailers() -> Vec<String> {
    vec!["Signed-off-by".into()]
}

pub fn default_signature_patterns() -> Vec<String> {
    vec![
        "Generated with [Claude Code]".into(),
        "Generated with Claude Code".into(),
        "Generated by Claude Code".into(),
        "🤖 Generated with".into(),
        "Co-Authored-By: Claude <noreply@anthropic.com>".into(),
        "https://claude.ai/code".into(),
        "Co-authored-by: Copilot".into(),
    ]
}

pub fn default_convention_types() -> Vec<String> {
    [
        "feat", "fix", "refactor", "chore", "docs", "test", "ci", "perf", "build", "style",
        "revert",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Governance {
    #[serde(default = "default_protected_trailers")]
    pub protected_trailers: Vec<String>,
    #[serde(default)]
    pub ai_attribution_policy: AiAttributionPolicy,
    #[serde(default = "default_signature_patterns")]
    pub signature_patterns: Vec<String>,
    #[serde(default = "default_convention_types")]
    pub convention_types: Vec<String>,
    /// Re-signe les commits produits par la réécriture si une clé de signature
    /// est configurée dans le dépôt (`user.signingkey` + `gpg.format`) — évite
    /// que la réécriture ne fasse perdre les signatures (B1). Défaut : off.
    #[serde(default)]
    pub resign_after_rewrite: bool,
}

impl Default for Governance {
    fn default() -> Self {
        Self {
            protected_trailers: default_protected_trailers(),
            ai_attribution_policy: AiAttributionPolicy::default(),
            signature_patterns: default_signature_patterns(),
            convention_types: default_convention_types(),
            resign_after_rewrite: false,
        }
    }
}

// ---------------------------------------------------------------------------
// Dépôts et commits
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepoRef {
    pub id: String,
    pub name: String,
    pub local_path: String,
    pub remote_url: Option<String>,
    pub default_branch: Option<String>,
    #[serde(default)]
    pub protected_branches: Vec<String>,
    #[serde(default)]
    pub governance: Governance,
    pub added_at: String,
    pub last_scanned_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchInfo {
    pub name: String,
    pub is_head: bool,
    pub upstream: Option<String>,
    pub tip: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitInfo {
    pub sha: String,
    pub short: String,
    pub parents: Vec<String>,
    pub author_name: String,
    pub author_email: String,
    pub date: String,
    pub subject: String,
    pub body: String,
    pub is_merge: bool,
    pub signed: bool,
    pub on_remote: bool,
    pub files_changed: usize,
    pub insertions: usize,
    pub deletions: usize,
    #[serde(default)]
    pub files: Vec<String>,
    pub trailers: Vec<(String, String)>,
}

impl CommitInfo {
    pub fn full_message(&self) -> String {
        if self.body.is_empty() {
            self.subject.clone()
        } else {
            format!("{}\n\n{}", self.subject, self.body)
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FlagKind {
    WeakMessage,
    NonConventional,
    AiSignature,
    OversizedNoBody,
    DuplicateMessage,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitFlag {
    pub sha: String,
    pub kind: FlagKind,
    pub score: u8,
    pub detail: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisReport {
    pub repo_id: String,
    pub branch: String,
    pub base: Option<String>,
    pub tip: String,
    pub total: usize,
    pub conform: usize,
    pub weak: usize,
    pub ai_signatures: usize,
    pub flags: Vec<CommitFlag>,
    pub generated_at: String,
}

// ---------------------------------------------------------------------------
// Plans de réécriture
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum Risk {
    #[default]
    Low,
    Medium,
    High,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum Operation {
    Reword {
        target: String,
        new_message: String,
    },
    /// Fusionne `targets` (contigus, ordre du segment) en un commit portant `new_message`.
    Squash {
        targets: Vec<String>,
        new_message: String,
    },
    /// Fusionne `targets` dans le premier d'entre eux en conservant son message.
    Fixup {
        targets: Vec<String>,
    },
    Drop {
        target: String,
        reason: String,
    },
    /// Ordre final des commits restants (leaders de groupes), du plus ancien au plus récent.
    Reorder {
        order: Vec<String>,
    },
    /// Découpe UN commit (C3) en plusieurs, par fichier : chaque `part` reçoit un
    /// sous-ensemble DISJOINT des fichiers modifiés par `target`, dans l'ordre
    /// donné. La réunion des `files` doit couvrir EXACTEMENT les fichiers du commit.
    /// Op exclusive (un plan de découpe ne contient qu'elle) ; segment linéaire.
    Split {
        target: String,
        parts: Vec<SplitPart>,
    },
}

/// Une part d'une découpe (C3) : les fichiers qui lui reviennent + son message.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SplitPart {
    pub files: Vec<String>,
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanOp {
    pub seq: u32,
    #[serde(flatten)]
    pub op: Operation,
    #[serde(default)]
    pub origin: String,
    #[serde(default)]
    pub risk: Risk,
    pub approved_by: Option<String>,
    pub approved_at: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanStatus {
    Draft,
    DryRunOk,
    Applied,
    RolledBack,
    Invalidated,
    /// Le rejeu du dry-run est EN PAUSE sur un conflit (C1) : résolution
    /// interactive attendue (résoudre → continuer, ou abandonner).
    Conflict,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Fingerprint {
    pub branch: String,
    pub tip: String,
    pub base: String,
}

/// Correspondance : plusieurs anciens SHA (groupe squashé) → un nouveau SHA.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShaMapping {
    pub old: Vec<String>,
    pub new: String,
}

/// Un fichier en conflit pendant un rejeu (C1) : `content` porte les marqueurs
/// `<<<<<<<`/`=======`/`>>>>>>>` que l'utilisateur édite pour résoudre.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConflictFile {
    pub path: String,
    pub content: String,
}

/// État d'un conflit de rejeu en pause (C1).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConflictInfo {
    pub files: Vec<ConflictFile>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    pub id: String,
    pub version: u32,
    pub repo_id: String,
    pub fingerprint: Fingerprint,
    pub status: PlanStatus,
    pub ops: Vec<PlanOp>,
    /// Hash du contenu (ops + empreinte) au moment du dernier dry-run réussi.
    pub dry_run_hash: Option<String>,
    pub preview_ref: Option<String>,
    pub backup_ref: Option<String>,
    pub backup_tag: Option<String>,
    pub mapping: Vec<ShaMapping>,
    pub created_at: String,
    pub dry_run_at: Option<String>,
    pub applied_at: Option<String>,
    pub error: Option<String>,
    /// Détail du conflit quand `status == Conflict` (C1).
    #[serde(default)]
    pub conflict: Option<ConflictInfo>,
}

// ---------------------------------------------------------------------------
// Propositions IA
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProposalStatus {
    Proposed,
    Accepted,
    Edited,
    Rejected,
    /// La skill a refusé de produire une proposition (garde-fou de gouvernance).
    Refused,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Proposal {
    pub id: String,
    pub repo_id: String,
    pub skill: String,
    pub skill_version: String,
    pub targets: Vec<String>,
    pub before: String,
    pub after: Option<String>,
    pub explanation: String,
    pub risk: Risk,
    pub status: ProposalStatus,
    /// Message final retenu par l'utilisateur (si Edited).
    pub decision: Option<String>,
    pub created_at: String,
}

// ---------------------------------------------------------------------------
// CI/CD
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CiKind {
    Github,
    GithubEnterprise,
    AzureDevops,
    AzureDevopsServer,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CiAccount {
    pub id: String,
    pub kind: CiKind,
    /// GitHub.com : https://api.github.com — GHES : https://hote/api/v3 —
    /// AzDO : https://dev.azure.com/{org} — Server : https://serveur/{collection}
    pub base_url: String,
    pub org: Option<String>,
    pub project: Option<String>,
    pub repo: Option<String>,
    /// Alias de l'entrée du coffre OS. Jamais le secret.
    pub token_ref: String,
    pub scopes: Vec<String>,
    pub added_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CiRun {
    pub account_id: String,
    pub pipeline_id: String,
    pub pipeline_name: String,
    pub run_id: String,
    pub status: String,
    pub result: Option<String>,
    pub branch: Option<String>,
    pub created_at: String,
    pub url: Option<String>,
    pub leased: bool,
    pub running: bool,
}

/// Artefact d'un run CI (F7 : purge de stockage). `size_bytes` sert à afficher
/// le volume récupérable avant la suppression.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CiArtifact {
    pub id: String,
    pub name: String,
    pub size_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RetentionRules {
    pub max_age_days: Option<u32>,
    pub keep_last_per_pipeline: u32,
    #[serde(default)]
    pub protect_branches: Vec<String>,
    #[serde(default)]
    pub protect_failed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RetentionPolicy {
    pub id: String,
    pub name: String,
    pub rules: RetentionRules,
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProtectedRun {
    pub run: CiRun,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulationReport {
    pub id: String,
    pub policy_id: String,
    pub account_id: String,
    pub generated_at: String,
    pub total: usize,
    pub candidates: Vec<CiRun>,
    pub protected: Vec<ProtectedRun>,
    pub kept_recent: usize,
    /// Empreinte du périmètre (compte + politique) — une exécution doit citer
    /// une simulation de même empreinte.
    pub scope_hash: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobMode {
    Simulation,
    Execution,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CleanupJob {
    pub id: String,
    pub policy_id: String,
    pub account_id: String,
    pub mode: JobMode,
    pub status: String,
    pub report: serde_json::Value,
    pub created_at: String,
    pub finished_at: Option<String>,
}

// ---------------------------------------------------------------------------
// IA
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AiProviderKind {
    /// Assistant déterministe local (aucun réseau) — repli par défaut.
    RuleBased,
    Ollama,
    OpenAiCompat,
    Anthropic,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiProviderConfig {
    pub id: String,
    pub kind: AiProviderKind,
    pub base_url: Option<String>,
    pub model: Option<String>,
    /// Alias coffre OS de la clé d'API (jamais la clé).
    pub key_ref: Option<String>,
    pub is_default: bool,
}

// ---------------------------------------------------------------------------
// Push assisté
// ---------------------------------------------------------------------------

/// Pull request ouverte détectée pour une branche (push assisté, F4).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrRef {
    pub number: u64,
    pub title: String,
    pub url: String,
}

// ---------------------------------------------------------------------------
// Audit
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditEvent {
    pub seq: i64,
    pub ts: String,
    pub actor: String,
    pub category: String,
    pub action: String,
    pub target: String,
    pub params: serde_json::Value,
    pub result: String,
}
